:em: {sp}--{sp}
:license-link: link:https://www.gnu.org/licenses/agpl-3.0.en.html

= CCHAT

TODO

== FEATURES

* *AUTHORITATIVE SERVER LOGIC* {em} A centralised "source of truth" model is utilised, where the server validates all client actions. This ensures state consistency across all connected nodes.

* *ASYNCHRONOUS MULTIPLEXING* {em} High performance I/O handling is achieved with the `select()` syscall. This allows the single threaded server to manage multiple concurrent client streams without blocking.

* *STATE-DRIVEN GUI* {em} The client-side GUI is built as a state machine, with the actual GUI rendering handled by *Raylib*. This facilitates transitions between login and chat screens.

* *SYNCHRONOUS IDENTITY HANDSHAKE* {em} A nickname registration protocol is integrated with server-side collision detection. This is done to avoid duplicate usernames.

* *ZERO-LATENCY UI FEEDBACK* {em} UI updates are performed real-time, including a blinking input cursor, backspace support with key-repeat and a dynamic scrolling message buffer.

* *LIGHTWEIGHT PROTOCOL* {em} Communication is optimised using a custom string-based protocol over raw TCP/IP sockets for minimal overhead.

* *MODULAR C ARCHITECTURE* {em} The codebase is written in a clean, `struct`-oriented fashion. This helps with maintainability and easy extension.

== BUILD INSTRUCTIONS

* Obtain a local copy of this repository with `git` and enter it
+
[source,]
----
  %  git clone https://github.com/vs-123/cchat.git
  %  cd cchat
----

=== CMAKE METHOD

* Create a `build` directory and enter it
+
[source,]
----
  %  mkdir build
  %  cd build
----

* Use CMake to build and link the project
+
[source,]
----
  %  cmake ..
  %  cmake --build .
  %  ls -Fa
  ./  ../  cchat-client*  cchat-server*  compile_commands.json  Makefile
----

* You may now proceed with <<usage-section, USAGE>>

=== MANUAL METHOD

* Create a `build` directory and enter it
+
[source,]
----
  %  mkdir build
  %  cd build
----

* Use the compiler of your choice to compile `src/client.c` and `src/server.c` with appropriate names
+
*[NOTE]* Make sure to link `raylib` and other necessary libraries when you compile the client.
+
[source,]
----
  %  clang -o cchat-client ../src/client.c -lraylib -lGL -lm -lpthread -ldl -lrt -lX11
  %  clang -o cchat-server ../src/server.c 
  %  ls -Fa
  ./  ../  cchat-client*  cchat-server*
----

* You may now proceed with <<usage-section, USAGE>>

[[usage-section]]
== USAGE

* Execute the server
+
[source,]
----
  %  ./cchat-server
  [INFO] SERVER START
----

* You may now launch one or more instances of the client and begin chatting
+
[source,]
----
  %  ./cchat-client
----

== LICENSE

This project is licensed under the *GNU Affero General Public License version 3.0 or later*.

*NO WARRANTY PROVIDED*

For more information, see `LICENSE` file or visit {license-link}.
